// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // conexión directa (no pooleada): prisma migrate necesita locks de
    // asesoría que el modo transaction pooling de pgbouncer no soporta
    url: process.env["DIRECT_URL"],
  },
});
